### ISSUE TITLE
error on ppm_scale calls

### ISSUE THREAD

**Issue by n-salvi** [BrownRE1991/OptimusPeak#19]
Hi, I am getting an error when I run the code, even on the example spectrum: 

Traceback (most recent call last):
  File "ThresholderGuas2.py", line 291, in <module>
    ppm_dim2 = uc_dim2.ppm_scale()
  File "/local2/data/anaconda3/envs/optimus/lib/python3.7/site-packages/nmrglue/fileio/fileiobase.py", line 276, in ppm_scale
    return np.linspace(x0, x1, self._size)
  File "<__array_function__ internals>", line 6, in linspace
  File "/local2/data/anaconda3/envs/optimus/lib/python3.7/site-packages/numpy/core/function_base.py", line 120, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer

I did a few tests, and the same error is produced whenever ppm_scale is calle. I don't think it is nmrglue though, as it seems all my other scripts seem to work

Any ideas ?

Thank you,

Nicola

**Comment by BrownRE1991** [comment]
I'll take a look. Which operating system are you using, and which file type (.ft2, .pipe, etc)?

**Comment by n-salvi** [comment]
Thank you for your reply, I tried both ft2 and pipe on Linux. I have a hunch that it might have to do with nmrglue versioning. If you can provide me with the exact library versions you are using, I can see if I can still reproduce the error

**Comment by BrownRE1991** [comment]
nmrglue version 0.10
numpy version 1.26.4
scipy version 1.13.1
python 3 version 3.12
